import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import NextAuthProvider from '@/providers/NextAuthProvider';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';
import { Suspense } from 'react';
import Loading from '@/components/Loading';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NextAuthProvider>
                    <Navbar />
                    <Toaster />
                    <Suspense fallback={<Loading/>}>
                        <div className="">{children}</div>
                    </Suspense>
                    <Footer />
                </NextAuthProvider>
            </body>
        </html>
    );
}
